/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package backtype.storm.daemon;

import backtype.storm.daemon.exceptions.AlreadyAliveException;
import backtype.storm.daemon.exceptions.InvalidTopologyException;
import backtype.storm.daemon.exceptions.NotAliveException;
import mrknmc.storm.topology.KillOptions;
import mrknmc.storm.topology.StormTopology;
import mrknmc.storm.topology.SubmitOptions;

public class Nimbus {

  public interface Iface {

    public void submitTopology(String name, String jsonConf, StormTopology topology) throws AlreadyAliveException, InvalidTopologyException, org.apache.thrift.TException;

    public void submitTopologyWithOpts(String name, String jsonConf, StormTopology topology, SubmitOptions options) throws AlreadyAliveException, InvalidTopologyException, org.apache.thrift.TException;

    public void killTopology(String name) throws NotAliveException, org.apache.thrift.TException;

    public void killTopologyWithOpts(String name, KillOptions options) throws NotAliveException, org.apache.thrift.TException;

    public void activate(String name) throws NotAliveException, org.apache.thrift.TException;

    public void deactivate(String name) throws NotAliveException, org.apache.thrift.TException;

    public String getNimbusConf() throws org.apache.thrift.TException;

//    public ClusterSummary getClusterInfo() throws org.apache.thrift.TException;

//    public TopologyInfo getTopologyInfo(String id) throws NotAliveException, org.apache.thrift.TException;

    public String getTopologyConf(String id) throws NotAliveException, org.apache.thrift.TException;

    public StormTopology getTopology(String id) throws NotAliveException, org.apache.thrift.TException;

    public StormTopology getUserTopology(String id) throws NotAliveException, org.apache.thrift.TException;

  }
}
